- name: Copy Logstash Configuration
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf


- name: Restart Logstash
  systemd:
    name: logstash
    state: restarted


- name: Waits for port 5044
  wait_for:
    port: 5044
    delay: 30
    timeout: 180
