route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: susarlarayudu166@gmail.com
    from: susarlarayudu166@gmail.com
    smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: {{SMTP_USERNAME}}
        auth_password: {{SMTP_PASSWORD}}
    require_tls: yes
