global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
         - localhost:9093

rule_files:
  - records.yaml
  - alerts.yaml

scrape_configs:
 - job_name: "ec2-nodes"
   ec2_sd_cofigs:
     - region: us_east_1
       access_key: {{ACCESS_KEY}}
       secret_key: {{ACCESS_SECRET}}
       port: 9100
       filters:
        - name: tag:Monitor
          values: ["yes"]
